import { ConfigComponent } from '@/types';

export const mockAlternatives: Record<string, ConfigComponent[]> = {
  Drivetrain: [
    { id: 'd1', category: 'Drivetrain', bikeType: 'Road', name: 'Shimano Dura-Ace Di2 R9200', price: 4200, weight: 2430, brand: 'Shimano', model: 'Dura-Ace Di2 R9200', specs: '12速, 电子变速' },
    { id: 'd2', category: 'Drivetrain', bikeType: 'Road', name: 'SRAM Red AXS', price: 4000, weight: 2380, brand: 'SRAM', model: 'Red AXS', specs: '12速, 无线电子变速' },
    { id: 'd3', category: 'Drivetrain', bikeType: 'Road', name: 'Campagnolo Super Record EPS', price: 4500, weight: 2450, brand: 'Campagnolo', model: 'Super Record EPS', specs: '12速, 电子变速' },
    { id: 'd4', category: 'Drivetrain', bikeType: 'Road', name: 'Shimano Ultegra Di2 R8100', price: 2800, weight: 2650, brand: 'Shimano', model: 'Ultegra Di2 R8100', specs: '12速, 电子变速' },
    { id: 'd5', category: 'Drivetrain', bikeType: 'Road', name: 'SRAM Force AXS', price: 2600, weight: 2600, brand: 'SRAM', model: 'Force AXS', specs: '12速, 无线电子变速' },
    { id: 'd6', category: 'Drivetrain', bikeType: 'MTB', name: 'SRAM XX1 Eagle AXS', price: 2500, weight: 1515, brand: 'SRAM', model: 'XX1 Eagle AXS', specs: '12速, 无线电子变速' },
    { id: 'd7', category: 'Drivetrain', bikeType: 'MTB', name: 'Shimano XTR Di2 M9100', price: 3200, weight: 1680, brand: 'Shimano', model: 'XTR Di2 M9100', specs: '12速, 电子变速' },
    { id: 'd8', category: 'Drivetrain', bikeType: 'MTB', name: 'SRAM GX Eagle', price: 850, weight: 2200, brand: 'SRAM', model: 'GX Eagle', specs: '12速, 机械变速' },
    { id: 'd9', category: 'Drivetrain', bikeType: 'Fold', name: 'Brompton 6-Speed', price: 400, weight: 1200, brand: 'Brompton', model: '6-Speed', specs: '6速, 内变速' },
    { id: 'd10', category: 'Drivetrain', bikeType: 'Fold', name: 'Shimano Nexus 8', price: 350, weight: 1400, brand: 'Shimano', model: 'Nexus 8', specs: '8速, 内变速' },
  ],
  Wheelset: [
    { id: 'w1', category: 'Wheelset', bikeType: 'Road', name: 'Roval Rapide CLX II', price: 2800, weight: 1520, brand: 'Roval', model: 'Rapide CLX II', specs: '碳轮, 50mm框高' },
    { id: 'w2', category: 'Wheelset', bikeType: 'Road', name: 'Zipp 454 NSW', price: 3200, weight: 1480, brand: 'Zipp', model: '454 NSW', specs: '碳轮, 波状轮圈' },
    { id: 'w3', category: 'Wheelset', bikeType: 'Road', name: 'Enve SES 4.5', price: 2900, weight: 1550, brand: 'Enve', model: 'SES 4.5', specs: '碳轮, 45mm框高' },
    { id: 'w4', category: 'Wheelset', bikeType: 'Road', name: 'Shimano Dura-Ace WH-R9200', price: 1800, weight: 1680, brand: 'Shimano', model: 'WH-R9200', specs: '铝轮, 30mm框高' },
    { id: 'w5', category: 'Wheelset', bikeType: 'MTB', name: 'Reserve 30|SL', price: 1800, weight: 1650, brand: 'Reserve', model: '30|SL', specs: '碳轮, 30mm内宽' },
    { id: 'w6', category: 'Wheelset', bikeType: 'MTB', name: 'Stan\'s No Tubes Flow MK4', price: 650, weight: 1950, brand: 'Stan\'s No Tubes', model: 'Flow MK4', specs: '铝轮, 30mm内宽' },
    { id: 'w7', category: 'Wheelset', bikeType: 'MTB', name: 'DT Swiss XMC 1200', price: 2400, weight: 1480, brand: 'DT Swiss', model: 'XMC 1200', specs: '碳轮, 25mm内宽' },
    { id: 'w8', category: 'Wheelset', bikeType: 'Fold', name: 'Brompton Superlight', price: 800, weight: 1100, brand: 'Brompton', model: 'Superlight', specs: '铝轮, 16寸' },
    { id: 'w9', category: 'Wheelset', bikeType: 'Fold', name: 'Birdy Carbon Wheels', price: 1200, weight: 950, brand: 'Birdy', model: 'Carbon', specs: '碳轮, 18寸' },
  ],
  Cockpit: [
    { id: 'c1', category: 'Cockpit', bikeType: 'Road', name: 'Roval Rapide Cockpit', price: 600, weight: 310, brand: 'Roval', model: 'Rapide Cockpit', specs: '一体把, 碳纤维' },
    { id: 'c2', category: 'Cockpit', bikeType: 'Road', name: 'Enve SES AR', price: 550, weight: 320, brand: 'Enve', model: 'SES AR', specs: '一体把, 空气动力学' },
    { id: 'c3', category: 'Cockpit', bikeType: 'Road', name: 'Shimano Pro Vibe', price: 300, weight: 380, brand: 'Shimano Pro', model: 'Vibe', specs: '分体把, 铝合金' },
    { id: 'c4', category: 'Cockpit', bikeType: 'MTB', name: 'Race Face Next R', price: 400, weight: 280, brand: 'Race Face', model: 'Next R', specs: '碳纤维, 35mm口径' },
    { id: 'c5', category: 'Cockpit', bikeType: 'MTB', name: 'Easton Haven', price: 320, weight: 340, brand: 'Easton', model: 'Haven', specs: '铝合金, 35mm口径' },
    { id: 'c6', category: 'Cockpit', bikeType: 'Fold', name: 'Brompton Handlebars', price: 150, weight: 450, brand: 'Brompton', model: 'Standard', specs: '铝合金, M把' },
  ],
  Tires: [
    { id: 't1', category: 'Tires', bikeType: 'Road', name: 'Turbo Cotton 28mm', price: 180, weight: 480, brand: 'Specialized', model: 'Turbo Cotton', specs: '开口胎, 28mm' },
    { id: 't2', category: 'Tires', bikeType: 'Road', name: 'Continental GP5000 S TR', price: 160, weight: 450, brand: 'Continental', model: 'GP5000 S TR', specs: '真空胎, 28mm' },
    { id: 't3', category: 'Tires', bikeType: 'Road', name: 'Schwalbe One Pro', price: 140, weight: 420, brand: 'Schwalbe', model: 'One Pro', specs: '开口胎, 25mm' },
    { id: 't4', category: 'Tires', bikeType: 'MTB', name: 'Maxxis Rekon 2.4', price: 160, weight: 1600, brand: 'Maxxis', model: 'Rekon', specs: '真空胎, 2.4寸' },
    { id: 't5', category: 'Tires', bikeType: 'MTB', name: 'Schwalbe Nobby Nic', price: 140, weight: 1450, brand: 'Schwalbe', model: 'Nobby Nic', specs: '真空胎, 2.25寸' },
    { id: 't6', category: 'Tires', bikeType: 'MTB', name: 'Continental Trail King', price: 150, weight: 1550, brand: 'Continental', model: 'Trail King', specs: '真空胎, 2.4寸' },
    { id: 't7', category: 'Tires', bikeType: 'Fold', name: 'Schwalbe Marathon Racer', price: 80, weight: 650, brand: 'Schwalbe', model: 'Marathon Racer', specs: '16x1.35' },
    { id: 't8', category: 'Tires', bikeType: 'Fold', name: 'Brompton Kevlar', price: 100, weight: 580, brand: 'Brompton', model: 'Kevlar', specs: '16x1.5, 防刺' },
  ],
  Suspension: [
    { id: 's1', category: 'Suspension', bikeType: 'MTB', name: 'Fox 34 Float Factory', price: 1050, weight: 1738, brand: 'Fox', model: '34 Float Factory', specs: '120mm行程, GRIP2阻尼' },
    { id: 's2', category: 'Suspension', bikeType: 'MTB', name: 'RockShox SID Ultimate', price: 950, weight: 1650, brand: 'RockShox', model: 'SID Ultimate', specs: '100mm行程, Charger Race Day' },
    { id: 's3', category: 'Suspension', bikeType: 'MTB', name: 'Fox 32 Step-Cast Factory', price: 1100, weight: 1580, brand: 'Fox', model: '32 Step-Cast Factory', specs: '100mm行程, 轻量XC' },
    { id: 's4', category: 'Suspension', bikeType: 'MTB', name: 'RockShox Pike Ultimate', price: 1200, weight: 1950, brand: 'RockShox', model: 'Pike Ultimate', specs: '130mm行程, Charger 2.1' },
    { id: 's5', category: 'Suspension', bikeType: 'MTB', name: 'Fox 36 Float Factory', price: 1300, weight: 2100, brand: 'Fox', model: '36 Float Factory', specs: '160mm行程, GRIP2阻尼' },
  ],
  Frame: [
    { id: 'f1', category: 'Frame', bikeType: 'Road', name: 'Specialized Tarmac SL8', price: 8000, weight: 890, brand: 'Specialized', model: 'Tarmac SL8', specs: '碳纤维, 竞赛级' },
    { id: 'f2', category: 'Frame', bikeType: 'Road', name: 'Trek Emonda SLR', price: 7500, weight: 920, brand: 'Trek', model: 'Emonda SLR', specs: '碳纤维, 超轻' },
    { id: 'f3', category: 'Frame', bikeType: 'Road', name: 'Canyon Ultimate CF SLX', price: 6800, weight: 950, brand: 'Canyon', model: 'Ultimate CF SLX', specs: '碳纤维, 气动优化' },
    { id: 'f4', category: 'Frame', bikeType: 'MTB', name: 'Santa Cruz Blur', price: 6500, weight: 2300, brand: 'Santa Cruz', model: 'Blur', specs: '碳纤维, XC竞赛' },
    { id: 'f5', category: 'Frame', bikeType: 'MTB', name: 'YT Izzo', price: 4800, weight: 2450, brand: 'YT Industries', model: 'Izzo', specs: '铝合金, XC/Trail' },
    { id: 'f6', category: 'Frame', bikeType: 'Fold', name: 'Brompton M6L', price: 3200, weight: 11800, brand: 'Brompton', model: 'M6L', specs: '钢质, 6速' },
    { id: 'f7', category: 'Frame', bikeType: 'Fold', name: 'Birdy GT', price: 4500, weight: 9200, brand: 'Birdy', model: 'GT', specs: '铝合金, 10速' },
    { id: 'f8', category: 'Frame', bikeType: 'Fold', name: 'Titanium Main Frame', price: 5800, weight: 8500, brand: 'Custom', model: 'Titanium', specs: '钛合金, 定制' },
    { id: 'f9', category: 'Frame', bikeType: 'Road', name: 'Colnago C68', price: 12000, weight: 880, brand: 'Colnago', model: 'C68', specs: '碳纤维, 旗舰级' },
    { id: 'f10', category: 'Frame', bikeType: 'MTB', name: 'Specialized Epic EVO', price: 5800, weight: 2500, brand: 'Specialized', model: 'Epic EVO', specs: '碳纤维, Trail' },
  ],
};
